name: Build Debian Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distrib: [debian/buster]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload package
        run: echo "Uploaded!"
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.deb
            os.json
