name: Build Debian Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distrib: [raspbian/buster]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload package
        uses: danielmundi/upload-packagecloud@main
        with:
          package-name: test-package.deb
          packagecloud-username: wlanpi
          packagecloud-repo: dev
          packagecloud-distrib: ${{ matrix.distrib }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
