name: Build Debian Packages

on: 
  push:
    tags-ignore:
      - "*"
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distrib: [debian/buster]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload package
        run: echo "Uploaded!"
        
      - name: Branch
        id: branch
        run: |
          echo ref = ${{ github.event.ref }}
          echo default_branch = ${{ github.event.repository.default_branch }}
          echo formatted_default = ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo are equal = ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo "::set-output name=version::${{ github.event.release.tag_name }}"
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.branch.outputs.version }}"
          files: |
            *.deb
            os.json
